project:
  type: website
  output-dir: docs
theme: cosmo 
website:
  title: "Dinki Di Data"
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - text: "Reports"
        href: reports/hello.qmd
execute:
  freeze: auto